"""empty message

Revision ID: c02166b87622
Revises: e17f6a2c2da5
Create Date: 2017-11-03 16:40:22.469446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02166b87622'
down_revision = 'e17f6a2c2da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('turns', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'turns')
    # ### end Alembic commands ###
