"""empty message

Revision ID: c3143b08493a
Revises: 
Create Date: 2017-11-05 18:29:17.052514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3143b08493a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('client', sa.String(length=128), nullable=True),
    sa.Column('vessel', sa.String(length=128), nullable=True),
    sa.Column('campaign', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_number'), 'projects', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('valves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valves_project_id'), 'valves', ['project_id'], unique=False)
    op.create_index(op.f('ix_valves_tag'), 'valves', ['tag'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('turns', sa.Float(), nullable=True),
    sa.Column('valve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['valve_id'], ['valves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_valve_id'), 'logs', ['valve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_valve_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_valves_tag'), table_name='valves')
    op.drop_index(op.f('ix_valves_project_id'), table_name='valves')
    op.drop_table('valves')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_number'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
