"""empty message

Revision ID: e17f6a2c2da5
Revises: 1672c80f8dd6
Create Date: 2017-11-02 22:29:45.577034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17f6a2c2da5'
down_revision = '1672c80f8dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valves', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valves', 'location')
    # ### end Alembic commands ###
